name: "Backlog Issue Updater"
description: "update an issue on Backlog"
inputs:
  host:
    required: true
  apiKey:
    required: true
  issueKey:
    required: true
  statusName:
    required: false
  customFieldsWithItems:
    required: false
  customFieldsWithoutItems:
    required: false
outputs:
  updated:
    description: "'true' or 'false'"
runs:
  using: "node12"
  main: "dist/index.js"
